name: Demo 1 - Workflow Local

on:
  push:
    branches: [master]


jobs:
  call-workflow-template:
    uses: franciscomoli/docker-test-action/.github/workflows/workflow6.yml@master
    # with:
    #   username: mona
    # secrets: inherit     

    